version: '3.8
services:
  # Django app
   backend_auth:
    container_name: prebel_auth
    build: 
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db_auth
      - redis

  # PostgresSQL
  db_auth:
    container_name: prebel_auth_api_postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prebel_jimmy
      POSTGRES_PASSWORD: Pr3B31_jimmy
      POSTGRES_DB: prebel_auth
    ports:
      - 5432:5432
    volumes:
      - .dbdata:var/lib/postgresql

  # kafka Queue
  # Redis:
    image: redis
    container_name: prebel_auth_api_redis
    ports:
      -"6379:6379